LEMMAS = {
    'tani': 'tani', 'tania': 'tani', 'tanie': 'tani', 'taniego': 'tani', 'taniej': 'tani',
    'okazja': 'okazja', 'okazji': 'okazja', 'okazję': 'okazja',
    'przystępne': 'przystępny', 'przystępny': 'przystępny', 'przystępna': 'przystępny',
    'drogi': 'drogi', 'droga': 'drogi', 'drogie': 'drogi', 'drogich': 'drogi', 'drogiego': 'drogi',
    'mały': 'mały', 'mała': 'mały', 'małe': 'mały', 'małych': 'mały', 'małego': 'mały',
    'średni': 'średni', 'średnia': 'średni', 'średnie': 'średni', 'średnich': 'średni',
    'duży': 'duży', 'duża': 'duży', 'duże': 'duży', 'dużych': 'duży', 'dużego': 'duży',
    'bardzo': 'bardzo',
    'nowy': 'nowy', 'nowa': 'nowy', 'nowe': 'nowy', 'nowych': 'nowy', 'nowego': 'nowy',
    'stary': 'stary', 'stara': 'stary', 'stare': 'stary', 'starych': 'stary', 'starego': 'stary',
    'współczesny': 'współczesny', 'współczesne': 'współczesny', 'współczesna': 'współczesny',
    'luksusowy': 'luksusowy', 'luksusowe': 'luksusowy', 'luksusowa': 'luksusowy',
    'ekskluzywne': 'ekskluzywny', 'ekskluzywny': 'ekskluzywny', 'ekskluzywna': 'ekskluzywny',
    'blisko': 'blisko', 'daleko': 'daleko', 'niedaleko': 'niedaleko',
    'blisko_centrum': 'blisko_centrum',
    'blisko_szkoła': 'blisko_szkoła',
    'blisko_klinika': 'blisko_klinika',
    'blisko_przedszkole': 'blisko_przedszkole',
    'blisko_apteka': 'blisko_apteka',
    'blisko_restauracja': 'blisko_restauracja',
    'blisko_uczelnia': 'blisko_uczelnia',
    'blisko_poczta': 'blisko_poczta',
    'bardzo_blisko_szkoła': 'bardzo_blisko_szkoła',
    'bardzo_blisko_klinika': 'bardzo_blisko_klinika',
    'bardzo_blisko_przedszkole': 'bardzo_blisko_przedszkole',
    'bardzo_blisko_apteka': 'bardzo_blisko_apteka',
    'bardzo_blisko_restauracja': 'bardzo_blisko_restauracja',
    'bardzo_blisko_uczelnia': 'bardzo_blisko_uczelnia',
    'bardzo_blisko_poczta': 'bardzo_blisko_poczta',
    'centrum': 'centrum', 'centrach': 'centrum', 'centru': 'centrum',
    'balkon': 'balkon', 'balkonu': 'balkon', 'balkony': 'balkon', 'balkonem': 'balkon',
    'winda': 'winda', 'windy': 'winda', 'windę': 'winda', 'windą': 'winda',
    'parking': 'parking', 'parkingu': 'parking', 'parkingi': 'parking', 'parkingiem': 'parking',
    'ochrona': 'ochrona', 'ochrony': 'ochrona', 'ochronę': 'ochrona', 'ochroną': 'ochrona',
    'piwnica': 'piwnica', 'piwnicy': 'piwnica', 'piwnicę': 'piwnica',
    'cena': 'cena', 'ceny': 'cena', 'cenę': 'cena',
    'od': 'od', 'z': 'z', 'do': 'do',
    'pokoje': 'pokój', 'pokój': 'pokój', 'pokoi': 'pokój',
    'kawalerka': 'kawalerka', 'kawalerki': 'kawalerka',
    'dwupokojowe': 'dwupokojowy', 'dwupokojowy': 'dwupokojowy',
    'trzypokojowe': 'trzypokojowy', 'trzypokojowy': 'trzypokojowy',
    'czteropokojowe': 'czteropokojowy', 'czteropokojowy': 'czteropokojowy',
    'rodzinne': 'rodzinny', 'rodzinny': 'rodzinny',
    'parter': 'parter', 'parterze': 'parter',
    'piętro': 'piętro', 'piętra': 'piętro', 'piętrze': 'piętro',
    'niskie': 'niski', 'niski': 'niski', 'niskiego': 'niski',
    'wysokie': 'wysoki', 'wysoki': 'wysoki', 'wysokiego': 'wysoki',
    'ostatnie': 'ostatni', 'ostatni': 'ostatni',
    'pierwsze': 'pierwszy', 'pierwszy': 'pierwszy',
    'budynek': 'budynek', 'budynku': 'budynek',
    'wieżowiec': 'wieżowiec', 'wieżowca': 'wieżowiec',
    'ścisłe': 'ścisły', 'ścisły': 'ścisły',
    'nowoczesne': 'nowoczesny', 'nowoczesny': 'nowoczesny',
    'świeżo': 'świeżo', 'wybudowane': 'wybudowany', 'wybudowany': 'wybudowany',
    'lat': 'rok', '90': '90',
    'PRL': 'prl', 'prl': 'prl',
    'blok': 'blok', 'bloku': 'blok',
    'przedwojenne': 'przedwojenny', 'przedwojenny': 'przedwojenny',
    'ogromne': 'ogromny', 'ogromny': 'ogromny',
    'przestronne': 'przestronny', 'przestronny': 'przestronny',
    'wielkie': 'wielki', 'wielki': 'wielki',
    'peryferie': 'peryferie', 'peryferiach': 'peryferie',
    'szkoła': 'szkoła', 'szkoły': 'szkoła', 'szkole': 'szkoła',
    'klinika': 'klinika', 'kliniki': 'klinika', 'klinice': 'klinika',
    'przedszkole': 'przedszkole', 'przedszkola': 'przedszkole',
    'apteka': 'apteka', 'apteki': 'apteka', 'aptece': 'apteka',
    'restauracja': 'restauracja', 'restauracji': 'restauracja',
    'uczelnia': 'uczelnia', 'uczelni': 'uczelnia',
    'poczta': 'poczta', 'poczty': 'poczta',
    'własnościowe': 'własnościowy', 'własnościowy': 'własnościowy',
    'spółdzielcze': 'spółdzielczy', 'spółdzielczy': 'spółdzielczy',
    'premium': 'premium',
    'stan': 'stan', 'stanu': 'stan',
    'remontu': 'remont', 'remont': 'remont',
    'odnowienia': 'odnowienie', 'odnowienie': 'odnowienie',
    'wykończone': 'wykończony', 'wykończony': 'wykończony',
    'cegła': 'cegła', 'cegły': 'cegła',
    'ceglany': 'ceglany', 'ceglana': 'ceglany', 'ceglane': 'ceglany',
    'wielka': 'wielki', 'płyta': 'płyta',
    'betonowy': 'betonowy', 'betonowa': 'betonowy', 'betonowe': 'betonowy',
    'mieszkalny': 'mieszkalny', 'mieszkalna': 'mieszkalny', 'mieszkalne': 'mieszkalny',
    'apartamentowiec': 'apartamentowiec', 'apartamentowca': 'apartamentowiec',
    'kamienica': 'kamienica', 'kamienicy': 'kamienica',
    
    # DZIELNICE WROCŁAWIA
    'bieńkowice': 'bieńkowice',
    'biskupin': 'biskupin', 'sępolno': 'sępolno', 'dąbie': 'dąbie', 'bartoszowice': 'bartoszowice',
    'borek': 'borek',
    'brochów': 'brochów',
    'gaj': 'gaj',
    'gajowice': 'gajowice',
    'grabiszyn': 'grabiszyn', 'grabiszynek': 'grabiszynek',
    'gądów': 'gądów', 'popowice': 'popowice',
    'huby': 'huby',
    'jagodno': 'jagodno',
    'jerzmanowo': 'jerzmanowo', 'jarnołtów': 'jarnołtów', 'strachowice': 'strachowice', 'osiniec': 'osiniec',
    'karłowice': 'karłowice', 'różanka': 'różanka',
    'klecina': 'klecina',
    'kleczków': 'kleczków',
    'kowale': 'kowale',
    'krzyki': 'krzyki', 'partynice': 'partynice',
    'księże': 'księże',
    'kuźniki': 'kuźniki',
    'leśnica': 'leśnica',
    'lipa': 'lipa', 'piotrowska': 'piotrowska',
    'maślice': 'maślice',
    'muchobór': 'muchobór', 'mały': 'mały', 'wielki': 'wielki',
    'nadodrze': 'nadodrze',
    'nowy': 'nowy', 'dwór': 'dwór',
    'oporów': 'oporów',
    'osobowice': 'osobowice', 'rędzin': 'rędzin',
    'ołbin': 'ołbin',
    'ołtaszyn': 'ołtaszyn',
    'pawłowice': 'pawłowice',
    'pilczyce': 'pilczyce', 'kozanów': 'kozanów',
    'plac': 'plac', 'grunwaldzki': 'grunwaldzki',
    'polanowice': 'polanowice', 'poświętne': 'poświętne', 'ligota': 'ligota',
    'powstańców': 'powstańców', 'śląskich': 'śląskich',
    'pracze': 'pracze', 'odrzańskie': 'odrzańskie',
    'przedmieście': 'przedmieście', 'oławskie': 'oławskie', 'świdnickie': 'świdnickie',
    'psie': 'psie', 'pole': 'pole', 'zawidawie': 'zawidawie',
    'sołtysowice': 'sołtysowice',
    'stare': 'stare', 'miasto': 'miasto',
    'strachocin': 'strachocin', 'swojczyce': 'swojczyce', 'wojnów': 'wojnów',
    'szczepin': 'szczepin',
    'tarnogaj': 'tarnogaj',
    'widawa': 'widawa',
    'wojszyce': 'wojszyce',
    'zacisze': 'zacisze', 'zalesie': 'zalesie', 'szczytniki': 'szczytniki',
    'świniary': 'świniary',
    'żerniki': 'żerniki',
}

def lemmatize_text(text):
    words = text.lower().split()
    return ' '.join([LEMMAS.get(w, w) for w in words])